export default {
  LOAD_FILE: 'LOAD_FILE',
  UPDATE_QUEST: 'UPDATE_QUEST',
  UPDATE_MISSON: 'UPDATE_MISSON',
  UPDATE_TASK: 'UPDATE_TASKPOINT',
  DELETE_QUEST: 'DELETE_QUEST',
  DELETE_MISSION: 'DELETE_MISSION',
  DELETE_TASK: 'DELETE_TASKPOINT',
  ADD_QUEST: 'ADD_QUEST',
  ADD_MISSION: 'ADD_MISSION',
  ADD_TASK: 'ADD_TASK',
};
