export default {
  LOAD_FILE: 'LOAD_FILE',
  UPDATE_QUEST: 'UPDATE_QUEST',
  UPDATE_MISSON: 'UPDATE_MISSON',
  UPDATE_TASKPOINT: 'UPDATE_TASKPOINT',
  DELETE_QUEST: 'DELETE_QUEST',
  DELETE_MISSION: 'DELETE_MISSION',
  DELETE_TASK: 'DELETE_TASKPOINT',
};
